In [2]:
import pandas as pd

In [7]:
n=3
df=pd.read_table('data/GSM4399753_Breast_1_d3.meth',nrows=10**n,engine='c')

In [14]:
df.iloc[110:120]

     chr1     9  +  CpG         0  0.1
110  chr1  1100  +  CpG  0.000000    0
111  chr1  1187  +  CpG  0.000000    0
112  chr1  1190  +  CpG  0.000000    0
113  chr1  1196  +  CpG  0.000000    0
114  chr1  1212  +  CpG  0.000000    0
115  chr1  1236  +  CpG  0.000000    0
116  chr1  1268  +  CpG  0.000000    0
117  chr1  1269  +  CpG  0.333333    3
118  chr1  1277  +  CpG  0.000000    0
119  chr1  1278  +  CpG  0.600000    5